import * as __source from "../compiler-sfc.js";
Object.defineProperties(__source["MagicString"], { name: { configurable: true, value: "MagicString" }, length: { configurable: true, value: 1 } });
Object.defineProperties(__source["babelParse"], { name: { configurable: true, value: "parse" }, length: { configurable: true, value: 2 } });
Object.defineProperties(__source["compileScript"], { name: { configurable: true, value: "compileScript" }, length: { configurable: true, value: 2 } });
Object.defineProperties(__source["compileStyle"], { name: { configurable: true, value: "compileStyle" }, length: { configurable: true, value: 1 } });
Object.defineProperties(__source["compileStyleAsync"], { name: { configurable: true, value: "compileStyleAsync" }, length: { configurable: true, value: 1 } });
Object.defineProperties(__source["compileTemplate"], { name: { configurable: true, value: "compileTemplate" }, length: { configurable: true, value: 1 } });
Object.defineProperties(__source["extractIdentifiers"], { name: { configurable: true, value: "extractIdentifiers" }, length: { configurable: true, value: 1 } });
Object.defineProperties(__source["extractRuntimeEmits"], { name: { configurable: true, value: "extractRuntimeEmits" }, length: { configurable: true, value: 1 } });
Object.defineProperties(__source["extractRuntimeProps"], { name: { configurable: true, value: "extractRuntimeProps" }, length: { configurable: true, value: 1 } });
Object.defineProperties(__source["generateCodeFrame"], { name: { configurable: true, value: "generateCodeFrame" }, length: { configurable: true, value: 1 } });
Object.defineProperties(__source["inferRuntimeType"], { name: { configurable: true, value: "inferRuntimeType" }, length: { configurable: true, value: 2 } });
Object.defineProperties(__source["invalidateTypeCache"], { name: { configurable: true, value: "invalidateTypeCache" }, length: { configurable: true, value: 1 } });
Object.defineProperties(__source["isInDestructureAssignment"], { name: { configurable: true, value: "isInDestructureAssignment" }, length: { configurable: true, value: 2 } });
Object.defineProperties(__source["isStaticProperty"], { name: { configurable: true, value: "isStaticProperty" }, length: { configurable: true, value: 1 } });
Object.defineProperties(__source["parse"], { name: { configurable: true, value: "parse$1" }, length: { configurable: true, value: 1 } });
Object.defineProperties(__source["registerTS"], { name: { configurable: true, value: "registerTS" }, length: { configurable: true, value: 1 } });
Object.defineProperties(__source["resolveTypeElements"], { name: { configurable: true, value: "resolveTypeElements" }, length: { configurable: true, value: 4 } });
Object.defineProperties(__source["rewriteDefault"], { name: { configurable: true, value: "rewriteDefault" }, length: { configurable: true, value: 3 } });
Object.defineProperties(__source["rewriteDefaultAST"], { name: { configurable: true, value: "rewriteDefaultAST" }, length: { configurable: true, value: 3 } });
Object.defineProperties(__source["shouldTransformRef"], { name: { configurable: true, value: "shouldTransformRef" }, length: { configurable: true, value: 0 } });
Object.defineProperties(__source["walk"], { name: { configurable: true, value: "walk" }, length: { configurable: true, value: 2 } });
Object.defineProperties(__source["walkIdentifiers"], { name: { configurable: true, value: "walkIdentifiers" }, length: { configurable: true, value: 2 } });
export { MagicString, babelParse, compileScript, compileStyle, compileStyleAsync, compileTemplate, errorMessages, extractIdentifiers, extractRuntimeEmits, extractRuntimeProps, generateCodeFrame, inferRuntimeType, invalidateTypeCache, isInDestructureAssignment, isStaticProperty, parse, parseCache, registerTS, resolveTypeElements, rewriteDefault, rewriteDefaultAST, shouldTransformRef, version, walk, walkIdentifiers } from "../compiler-sfc.js";
